// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ModelHasPermission is the predicate function for modelhaspermission builders.
type ModelHasPermission func(*sql.Selector)

// ModelHasRole is the predicate function for modelhasrole builders.
type ModelHasRole func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RoleHasPermission is the predicate function for rolehaspermission builders.
type RoleHasPermission func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantUser is the predicate function for tenantuser builders.
type TenantUser func(*sql.Selector)
