// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ModelHasPermissionsColumns holds the columns for the "model_has_permissions" table.
	ModelHasPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "permission_id", Type: field.TypeUint},
		{Name: "model_type", Type: field.TypeString, Size: 255},
		{Name: "model_id", Type: field.TypeUint},
		{Name: "tenant_id", Type: field.TypeString, Nullable: true, Size: 100},
	}
	// ModelHasPermissionsTable holds the schema information for the "model_has_permissions" table.
	ModelHasPermissionsTable = &schema.Table{
		Name:       "model_has_permissions",
		Columns:    ModelHasPermissionsColumns,
		PrimaryKey: []*schema.Column{ModelHasPermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_model_permissions_unique",
				Unique:  true,
				Columns: []*schema.Column{ModelHasPermissionsColumns[1], ModelHasPermissionsColumns[2], ModelHasPermissionsColumns[3]},
			},
			{
				Name:    "idx_model_permissions_tenant",
				Unique:  false,
				Columns: []*schema.Column{ModelHasPermissionsColumns[4]},
			},
		},
	}
	// ModelHasRolesColumns holds the columns for the "model_has_roles" table.
	ModelHasRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "role_id", Type: field.TypeUint},
		{Name: "model_type", Type: field.TypeString, Size: 255},
		{Name: "model_id", Type: field.TypeUint},
		{Name: "tenant_id", Type: field.TypeString, Nullable: true, Size: 100},
	}
	// ModelHasRolesTable holds the schema information for the "model_has_roles" table.
	ModelHasRolesTable = &schema.Table{
		Name:       "model_has_roles",
		Columns:    ModelHasRolesColumns,
		PrimaryKey: []*schema.Column{ModelHasRolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_model_roles_unique",
				Unique:  true,
				Columns: []*schema.Column{ModelHasRolesColumns[1], ModelHasRolesColumns[2], ModelHasRolesColumns[3]},
			},
			{
				Name:    "idx_model_roles_tenant",
				Unique:  false,
				Columns: []*schema.Column{ModelHasRolesColumns[4]},
			},
		},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "guard_name", Type: field.TypeString, Size: 100, Default: "web"},
		{Name: "tenant_id", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_permissions_name_guard_tenant",
				Unique:  true,
				Columns: []*schema.Column{PermissionsColumns[1], PermissionsColumns[2], PermissionsColumns[3]},
			},
			{
				Name:    "idx_permissions_tenant",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[3]},
			},
			{
				Name:    "idx_permissions_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[6]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "guard_name", Type: field.TypeString, Size: 100, Default: "web"},
		{Name: "tenant_id", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_roles_name_guard_tenant",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[1], RolesColumns[2], RolesColumns[3]},
			},
			{
				Name:    "idx_roles_tenant",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[3]},
			},
			{
				Name:    "idx_roles_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[6]},
			},
		},
	}
	// RoleHasPermissionsColumns holds the columns for the "role_has_permissions" table.
	RoleHasPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "permission_id", Type: field.TypeUint},
		{Name: "role_id", Type: field.TypeUint},
		{Name: "tenant_id", Type: field.TypeString, Nullable: true, Size: 100},
	}
	// RoleHasPermissionsTable holds the schema information for the "role_has_permissions" table.
	RoleHasPermissionsTable = &schema.Table{
		Name:       "role_has_permissions",
		Columns:    RoleHasPermissionsColumns,
		PrimaryKey: []*schema.Column{RoleHasPermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_role_permissions_unique",
				Unique:  true,
				Columns: []*schema.Column{RoleHasPermissionsColumns[1], RoleHasPermissionsColumns[2]},
			},
			{
				Name:    "idx_role_permissions_tenant",
				Unique:  false,
				Columns: []*schema.Column{RoleHasPermissionsColumns[3]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "slug", Type: field.TypeString, Size: 255},
		{Name: "domain", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "logo", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "owner_id", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "config", Type: field.TypeString, Nullable: true},
		{Name: "settings", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_tenants_slug",
				Unique:  true,
				Columns: []*schema.Column{TenantsColumns[2]},
			},
			{
				Name:    "idx_tenants_domain",
				Unique:  true,
				Columns: []*schema.Column{TenantsColumns[3]},
			},
			{
				Name:    "idx_tenants_owner",
				Unique:  false,
				Columns: []*schema.Column{TenantsColumns[6]},
			},
			{
				Name:    "idx_tenants_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{TenantsColumns[11]},
			},
		},
	}
	// TenantUserColumns holds the columns for the "tenant_user" table.
	TenantUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "user_id", Type: field.TypeString, Size: 100},
		{Name: "tenant_id", Type: field.TypeString, Size: 100},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// TenantUserTable holds the schema information for the "tenant_user" table.
	TenantUserTable = &schema.Table{
		Name:       "tenant_user",
		Columns:    TenantUserColumns,
		PrimaryKey: []*schema.Column{TenantUserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_tenant_user_unique",
				Unique:  true,
				Columns: []*schema.Column{TenantUserColumns[1], TenantUserColumns[2]},
			},
			{
				Name:    "idx_tenant_user_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{TenantUserColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ModelHasPermissionsTable,
		ModelHasRolesTable,
		PermissionsTable,
		RolesTable,
		RoleHasPermissionsTable,
		TenantsTable,
		TenantUserTable,
	}
)

func init() {
	ModelHasPermissionsTable.Annotation = &entsql.Annotation{
		Table: "model_has_permissions",
	}
	ModelHasRolesTable.Annotation = &entsql.Annotation{
		Table: "model_has_roles",
	}
	PermissionsTable.Annotation = &entsql.Annotation{
		Table: "permissions",
	}
	RolesTable.Annotation = &entsql.Annotation{
		Table: "roles",
	}
	RoleHasPermissionsTable.Annotation = &entsql.Annotation{
		Table: "role_has_permissions",
	}
	TenantsTable.Annotation = &entsql.Annotation{
		Table: "tenants",
	}
	TenantUserTable.Annotation = &entsql.Annotation{
		Table: "tenant_user",
	}
}
