// Code generated by ent, DO NOT EDIT.

package rolehaspermission

import (
	"entgo.io/ent/dialect/sql"
	"github.com/mwangaben/permission/storage/entstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldLTE(FieldID, id))
}

// PermissionID applies equality check predicate on the "permission_id" field. It's identical to PermissionIDEQ.
func PermissionID(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldEQ(FieldPermissionID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldEQ(FieldRoleID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldEQ(FieldTenantID, v))
}

// PermissionIDEQ applies the EQ predicate on the "permission_id" field.
func PermissionIDEQ(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldEQ(FieldPermissionID, v))
}

// PermissionIDNEQ applies the NEQ predicate on the "permission_id" field.
func PermissionIDNEQ(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldNEQ(FieldPermissionID, v))
}

// PermissionIDIn applies the In predicate on the "permission_id" field.
func PermissionIDIn(vs ...uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldIn(FieldPermissionID, vs...))
}

// PermissionIDNotIn applies the NotIn predicate on the "permission_id" field.
func PermissionIDNotIn(vs ...uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldNotIn(FieldPermissionID, vs...))
}

// PermissionIDGT applies the GT predicate on the "permission_id" field.
func PermissionIDGT(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldGT(FieldPermissionID, v))
}

// PermissionIDGTE applies the GTE predicate on the "permission_id" field.
func PermissionIDGTE(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldGTE(FieldPermissionID, v))
}

// PermissionIDLT applies the LT predicate on the "permission_id" field.
func PermissionIDLT(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldLT(FieldPermissionID, v))
}

// PermissionIDLTE applies the LTE predicate on the "permission_id" field.
func PermissionIDLTE(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldLTE(FieldPermissionID, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v uint) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldLTE(FieldRoleID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldNotNull(FieldTenantID))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.FieldContainsFold(FieldTenantID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoleHasPermission) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoleHasPermission) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoleHasPermission) predicate.RoleHasPermission {
	return predicate.RoleHasPermission(sql.NotPredicates(p))
}
