// Code generated by ent, DO NOT EDIT.

package modelhaspermission

import (
	"entgo.io/ent/dialect/sql"
	"github.com/mwangaben/permission/storage/entstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldLTE(FieldID, id))
}

// PermissionID applies equality check predicate on the "permission_id" field. It's identical to PermissionIDEQ.
func PermissionID(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEQ(FieldPermissionID, v))
}

// ModelType applies equality check predicate on the "model_type" field. It's identical to ModelTypeEQ.
func ModelType(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEQ(FieldModelType, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEQ(FieldModelID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEQ(FieldTenantID, v))
}

// PermissionIDEQ applies the EQ predicate on the "permission_id" field.
func PermissionIDEQ(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEQ(FieldPermissionID, v))
}

// PermissionIDNEQ applies the NEQ predicate on the "permission_id" field.
func PermissionIDNEQ(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNEQ(FieldPermissionID, v))
}

// PermissionIDIn applies the In predicate on the "permission_id" field.
func PermissionIDIn(vs ...uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldIn(FieldPermissionID, vs...))
}

// PermissionIDNotIn applies the NotIn predicate on the "permission_id" field.
func PermissionIDNotIn(vs ...uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNotIn(FieldPermissionID, vs...))
}

// PermissionIDGT applies the GT predicate on the "permission_id" field.
func PermissionIDGT(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldGT(FieldPermissionID, v))
}

// PermissionIDGTE applies the GTE predicate on the "permission_id" field.
func PermissionIDGTE(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldGTE(FieldPermissionID, v))
}

// PermissionIDLT applies the LT predicate on the "permission_id" field.
func PermissionIDLT(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldLT(FieldPermissionID, v))
}

// PermissionIDLTE applies the LTE predicate on the "permission_id" field.
func PermissionIDLTE(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldLTE(FieldPermissionID, v))
}

// ModelTypeEQ applies the EQ predicate on the "model_type" field.
func ModelTypeEQ(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEQ(FieldModelType, v))
}

// ModelTypeNEQ applies the NEQ predicate on the "model_type" field.
func ModelTypeNEQ(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNEQ(FieldModelType, v))
}

// ModelTypeIn applies the In predicate on the "model_type" field.
func ModelTypeIn(vs ...string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldIn(FieldModelType, vs...))
}

// ModelTypeNotIn applies the NotIn predicate on the "model_type" field.
func ModelTypeNotIn(vs ...string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNotIn(FieldModelType, vs...))
}

// ModelTypeGT applies the GT predicate on the "model_type" field.
func ModelTypeGT(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldGT(FieldModelType, v))
}

// ModelTypeGTE applies the GTE predicate on the "model_type" field.
func ModelTypeGTE(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldGTE(FieldModelType, v))
}

// ModelTypeLT applies the LT predicate on the "model_type" field.
func ModelTypeLT(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldLT(FieldModelType, v))
}

// ModelTypeLTE applies the LTE predicate on the "model_type" field.
func ModelTypeLTE(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldLTE(FieldModelType, v))
}

// ModelTypeContains applies the Contains predicate on the "model_type" field.
func ModelTypeContains(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldContains(FieldModelType, v))
}

// ModelTypeHasPrefix applies the HasPrefix predicate on the "model_type" field.
func ModelTypeHasPrefix(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldHasPrefix(FieldModelType, v))
}

// ModelTypeHasSuffix applies the HasSuffix predicate on the "model_type" field.
func ModelTypeHasSuffix(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldHasSuffix(FieldModelType, v))
}

// ModelTypeEqualFold applies the EqualFold predicate on the "model_type" field.
func ModelTypeEqualFold(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEqualFold(FieldModelType, v))
}

// ModelTypeContainsFold applies the ContainsFold predicate on the "model_type" field.
func ModelTypeContainsFold(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldContainsFold(FieldModelType, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v uint) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldLTE(FieldModelID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldNotNull(FieldTenantID))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.FieldContainsFold(FieldTenantID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelHasPermission) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelHasPermission) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelHasPermission) predicate.ModelHasPermission {
	return predicate.ModelHasPermission(sql.NotPredicates(p))
}
