// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/mwangaben/permission/storage/entstore/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/mwangaben/permission/storage/entstore/ent/modelhaspermission"
	"github.com/mwangaben/permission/storage/entstore/ent/modelhasrole"
	"github.com/mwangaben/permission/storage/entstore/ent/permission"
	"github.com/mwangaben/permission/storage/entstore/ent/role"
	"github.com/mwangaben/permission/storage/entstore/ent/rolehaspermission"
	"github.com/mwangaben/permission/storage/entstore/ent/tenant"
	"github.com/mwangaben/permission/storage/entstore/ent/tenantuser"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ModelHasPermission is the client for interacting with the ModelHasPermission builders.
	ModelHasPermission *ModelHasPermissionClient
	// ModelHasRole is the client for interacting with the ModelHasRole builders.
	ModelHasRole *ModelHasRoleClient
	// Permission is the client for interacting with the Permission builders.
	Permission *PermissionClient
	// Role is the client for interacting with the Role builders.
	Role *RoleClient
	// RoleHasPermission is the client for interacting with the RoleHasPermission builders.
	RoleHasPermission *RoleHasPermissionClient
	// Tenant is the client for interacting with the Tenant builders.
	Tenant *TenantClient
	// TenantUser is the client for interacting with the TenantUser builders.
	TenantUser *TenantUserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ModelHasPermission = NewModelHasPermissionClient(c.config)
	c.ModelHasRole = NewModelHasRoleClient(c.config)
	c.Permission = NewPermissionClient(c.config)
	c.Role = NewRoleClient(c.config)
	c.RoleHasPermission = NewRoleHasPermissionClient(c.config)
	c.Tenant = NewTenantClient(c.config)
	c.TenantUser = NewTenantUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		ModelHasPermission: NewModelHasPermissionClient(cfg),
		ModelHasRole:       NewModelHasRoleClient(cfg),
		Permission:         NewPermissionClient(cfg),
		Role:               NewRoleClient(cfg),
		RoleHasPermission:  NewRoleHasPermissionClient(cfg),
		Tenant:             NewTenantClient(cfg),
		TenantUser:         NewTenantUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		ModelHasPermission: NewModelHasPermissionClient(cfg),
		ModelHasRole:       NewModelHasRoleClient(cfg),
		Permission:         NewPermissionClient(cfg),
		Role:               NewRoleClient(cfg),
		RoleHasPermission:  NewRoleHasPermissionClient(cfg),
		Tenant:             NewTenantClient(cfg),
		TenantUser:         NewTenantUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ModelHasPermission.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.ModelHasPermission, c.ModelHasRole, c.Permission, c.Role, c.RoleHasPermission,
		c.Tenant, c.TenantUser,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.ModelHasPermission, c.ModelHasRole, c.Permission, c.Role, c.RoleHasPermission,
		c.Tenant, c.TenantUser,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ModelHasPermissionMutation:
		return c.ModelHasPermission.mutate(ctx, m)
	case *ModelHasRoleMutation:
		return c.ModelHasRole.mutate(ctx, m)
	case *PermissionMutation:
		return c.Permission.mutate(ctx, m)
	case *RoleMutation:
		return c.Role.mutate(ctx, m)
	case *RoleHasPermissionMutation:
		return c.RoleHasPermission.mutate(ctx, m)
	case *TenantMutation:
		return c.Tenant.mutate(ctx, m)
	case *TenantUserMutation:
		return c.TenantUser.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ModelHasPermissionClient is a client for the ModelHasPermission schema.
type ModelHasPermissionClient struct {
	config
}

// NewModelHasPermissionClient returns a client for the ModelHasPermission from the given config.
func NewModelHasPermissionClient(c config) *ModelHasPermissionClient {
	return &ModelHasPermissionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `modelhaspermission.Hooks(f(g(h())))`.
func (c *ModelHasPermissionClient) Use(hooks ...Hook) {
	c.hooks.ModelHasPermission = append(c.hooks.ModelHasPermission, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `modelhaspermission.Intercept(f(g(h())))`.
func (c *ModelHasPermissionClient) Intercept(interceptors ...Interceptor) {
	c.inters.ModelHasPermission = append(c.inters.ModelHasPermission, interceptors...)
}

// Create returns a builder for creating a ModelHasPermission entity.
func (c *ModelHasPermissionClient) Create() *ModelHasPermissionCreate {
	mutation := newModelHasPermissionMutation(c.config, OpCreate)
	return &ModelHasPermissionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ModelHasPermission entities.
func (c *ModelHasPermissionClient) CreateBulk(builders ...*ModelHasPermissionCreate) *ModelHasPermissionCreateBulk {
	return &ModelHasPermissionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ModelHasPermissionClient) MapCreateBulk(slice any, setFunc func(*ModelHasPermissionCreate, int)) *ModelHasPermissionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ModelHasPermissionCreateBulk{err: fmt.Errorf("calling to ModelHasPermissionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ModelHasPermissionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ModelHasPermissionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ModelHasPermission.
func (c *ModelHasPermissionClient) Update() *ModelHasPermissionUpdate {
	mutation := newModelHasPermissionMutation(c.config, OpUpdate)
	return &ModelHasPermissionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ModelHasPermissionClient) UpdateOne(_m *ModelHasPermission) *ModelHasPermissionUpdateOne {
	mutation := newModelHasPermissionMutation(c.config, OpUpdateOne, withModelHasPermission(_m))
	return &ModelHasPermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ModelHasPermissionClient) UpdateOneID(id uint) *ModelHasPermissionUpdateOne {
	mutation := newModelHasPermissionMutation(c.config, OpUpdateOne, withModelHasPermissionID(id))
	return &ModelHasPermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ModelHasPermission.
func (c *ModelHasPermissionClient) Delete() *ModelHasPermissionDelete {
	mutation := newModelHasPermissionMutation(c.config, OpDelete)
	return &ModelHasPermissionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ModelHasPermissionClient) DeleteOne(_m *ModelHasPermission) *ModelHasPermissionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ModelHasPermissionClient) DeleteOneID(id uint) *ModelHasPermissionDeleteOne {
	builder := c.Delete().Where(modelhaspermission.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ModelHasPermissionDeleteOne{builder}
}

// Query returns a query builder for ModelHasPermission.
func (c *ModelHasPermissionClient) Query() *ModelHasPermissionQuery {
	return &ModelHasPermissionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeModelHasPermission},
		inters: c.Interceptors(),
	}
}

// Get returns a ModelHasPermission entity by its id.
func (c *ModelHasPermissionClient) Get(ctx context.Context, id uint) (*ModelHasPermission, error) {
	return c.Query().Where(modelhaspermission.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ModelHasPermissionClient) GetX(ctx context.Context, id uint) *ModelHasPermission {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ModelHasPermissionClient) Hooks() []Hook {
	return c.hooks.ModelHasPermission
}

// Interceptors returns the client interceptors.
func (c *ModelHasPermissionClient) Interceptors() []Interceptor {
	return c.inters.ModelHasPermission
}

func (c *ModelHasPermissionClient) mutate(ctx context.Context, m *ModelHasPermissionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ModelHasPermissionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ModelHasPermissionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ModelHasPermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ModelHasPermissionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ModelHasPermission mutation op: %q", m.Op())
	}
}

// ModelHasRoleClient is a client for the ModelHasRole schema.
type ModelHasRoleClient struct {
	config
}

// NewModelHasRoleClient returns a client for the ModelHasRole from the given config.
func NewModelHasRoleClient(c config) *ModelHasRoleClient {
	return &ModelHasRoleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `modelhasrole.Hooks(f(g(h())))`.
func (c *ModelHasRoleClient) Use(hooks ...Hook) {
	c.hooks.ModelHasRole = append(c.hooks.ModelHasRole, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `modelhasrole.Intercept(f(g(h())))`.
func (c *ModelHasRoleClient) Intercept(interceptors ...Interceptor) {
	c.inters.ModelHasRole = append(c.inters.ModelHasRole, interceptors...)
}

// Create returns a builder for creating a ModelHasRole entity.
func (c *ModelHasRoleClient) Create() *ModelHasRoleCreate {
	mutation := newModelHasRoleMutation(c.config, OpCreate)
	return &ModelHasRoleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ModelHasRole entities.
func (c *ModelHasRoleClient) CreateBulk(builders ...*ModelHasRoleCreate) *ModelHasRoleCreateBulk {
	return &ModelHasRoleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ModelHasRoleClient) MapCreateBulk(slice any, setFunc func(*ModelHasRoleCreate, int)) *ModelHasRoleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ModelHasRoleCreateBulk{err: fmt.Errorf("calling to ModelHasRoleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ModelHasRoleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ModelHasRoleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ModelHasRole.
func (c *ModelHasRoleClient) Update() *ModelHasRoleUpdate {
	mutation := newModelHasRoleMutation(c.config, OpUpdate)
	return &ModelHasRoleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ModelHasRoleClient) UpdateOne(_m *ModelHasRole) *ModelHasRoleUpdateOne {
	mutation := newModelHasRoleMutation(c.config, OpUpdateOne, withModelHasRole(_m))
	return &ModelHasRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ModelHasRoleClient) UpdateOneID(id uint) *ModelHasRoleUpdateOne {
	mutation := newModelHasRoleMutation(c.config, OpUpdateOne, withModelHasRoleID(id))
	return &ModelHasRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ModelHasRole.
func (c *ModelHasRoleClient) Delete() *ModelHasRoleDelete {
	mutation := newModelHasRoleMutation(c.config, OpDelete)
	return &ModelHasRoleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ModelHasRoleClient) DeleteOne(_m *ModelHasRole) *ModelHasRoleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ModelHasRoleClient) DeleteOneID(id uint) *ModelHasRoleDeleteOne {
	builder := c.Delete().Where(modelhasrole.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ModelHasRoleDeleteOne{builder}
}

// Query returns a query builder for ModelHasRole.
func (c *ModelHasRoleClient) Query() *ModelHasRoleQuery {
	return &ModelHasRoleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeModelHasRole},
		inters: c.Interceptors(),
	}
}

// Get returns a ModelHasRole entity by its id.
func (c *ModelHasRoleClient) Get(ctx context.Context, id uint) (*ModelHasRole, error) {
	return c.Query().Where(modelhasrole.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ModelHasRoleClient) GetX(ctx context.Context, id uint) *ModelHasRole {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ModelHasRoleClient) Hooks() []Hook {
	return c.hooks.ModelHasRole
}

// Interceptors returns the client interceptors.
func (c *ModelHasRoleClient) Interceptors() []Interceptor {
	return c.inters.ModelHasRole
}

func (c *ModelHasRoleClient) mutate(ctx context.Context, m *ModelHasRoleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ModelHasRoleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ModelHasRoleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ModelHasRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ModelHasRoleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ModelHasRole mutation op: %q", m.Op())
	}
}

// PermissionClient is a client for the Permission schema.
type PermissionClient struct {
	config
}

// NewPermissionClient returns a client for the Permission from the given config.
func NewPermissionClient(c config) *PermissionClient {
	return &PermissionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `permission.Hooks(f(g(h())))`.
func (c *PermissionClient) Use(hooks ...Hook) {
	c.hooks.Permission = append(c.hooks.Permission, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `permission.Intercept(f(g(h())))`.
func (c *PermissionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Permission = append(c.inters.Permission, interceptors...)
}

// Create returns a builder for creating a Permission entity.
func (c *PermissionClient) Create() *PermissionCreate {
	mutation := newPermissionMutation(c.config, OpCreate)
	return &PermissionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Permission entities.
func (c *PermissionClient) CreateBulk(builders ...*PermissionCreate) *PermissionCreateBulk {
	return &PermissionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PermissionClient) MapCreateBulk(slice any, setFunc func(*PermissionCreate, int)) *PermissionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PermissionCreateBulk{err: fmt.Errorf("calling to PermissionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PermissionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PermissionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Permission.
func (c *PermissionClient) Update() *PermissionUpdate {
	mutation := newPermissionMutation(c.config, OpUpdate)
	return &PermissionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PermissionClient) UpdateOne(_m *Permission) *PermissionUpdateOne {
	mutation := newPermissionMutation(c.config, OpUpdateOne, withPermission(_m))
	return &PermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PermissionClient) UpdateOneID(id uint) *PermissionUpdateOne {
	mutation := newPermissionMutation(c.config, OpUpdateOne, withPermissionID(id))
	return &PermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Permission.
func (c *PermissionClient) Delete() *PermissionDelete {
	mutation := newPermissionMutation(c.config, OpDelete)
	return &PermissionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PermissionClient) DeleteOne(_m *Permission) *PermissionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PermissionClient) DeleteOneID(id uint) *PermissionDeleteOne {
	builder := c.Delete().Where(permission.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PermissionDeleteOne{builder}
}

// Query returns a query builder for Permission.
func (c *PermissionClient) Query() *PermissionQuery {
	return &PermissionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePermission},
		inters: c.Interceptors(),
	}
}

// Get returns a Permission entity by its id.
func (c *PermissionClient) Get(ctx context.Context, id uint) (*Permission, error) {
	return c.Query().Where(permission.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PermissionClient) GetX(ctx context.Context, id uint) *Permission {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PermissionClient) Hooks() []Hook {
	return c.hooks.Permission
}

// Interceptors returns the client interceptors.
func (c *PermissionClient) Interceptors() []Interceptor {
	return c.inters.Permission
}

func (c *PermissionClient) mutate(ctx context.Context, m *PermissionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PermissionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PermissionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PermissionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Permission mutation op: %q", m.Op())
	}
}

// RoleClient is a client for the Role schema.
type RoleClient struct {
	config
}

// NewRoleClient returns a client for the Role from the given config.
func NewRoleClient(c config) *RoleClient {
	return &RoleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `role.Hooks(f(g(h())))`.
func (c *RoleClient) Use(hooks ...Hook) {
	c.hooks.Role = append(c.hooks.Role, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `role.Intercept(f(g(h())))`.
func (c *RoleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Role = append(c.inters.Role, interceptors...)
}

// Create returns a builder for creating a Role entity.
func (c *RoleClient) Create() *RoleCreate {
	mutation := newRoleMutation(c.config, OpCreate)
	return &RoleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Role entities.
func (c *RoleClient) CreateBulk(builders ...*RoleCreate) *RoleCreateBulk {
	return &RoleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RoleClient) MapCreateBulk(slice any, setFunc func(*RoleCreate, int)) *RoleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RoleCreateBulk{err: fmt.Errorf("calling to RoleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RoleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RoleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Role.
func (c *RoleClient) Update() *RoleUpdate {
	mutation := newRoleMutation(c.config, OpUpdate)
	return &RoleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RoleClient) UpdateOne(_m *Role) *RoleUpdateOne {
	mutation := newRoleMutation(c.config, OpUpdateOne, withRole(_m))
	return &RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RoleClient) UpdateOneID(id uint) *RoleUpdateOne {
	mutation := newRoleMutation(c.config, OpUpdateOne, withRoleID(id))
	return &RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Role.
func (c *RoleClient) Delete() *RoleDelete {
	mutation := newRoleMutation(c.config, OpDelete)
	return &RoleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RoleClient) DeleteOne(_m *Role) *RoleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RoleClient) DeleteOneID(id uint) *RoleDeleteOne {
	builder := c.Delete().Where(role.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RoleDeleteOne{builder}
}

// Query returns a query builder for Role.
func (c *RoleClient) Query() *RoleQuery {
	return &RoleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRole},
		inters: c.Interceptors(),
	}
}

// Get returns a Role entity by its id.
func (c *RoleClient) Get(ctx context.Context, id uint) (*Role, error) {
	return c.Query().Where(role.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RoleClient) GetX(ctx context.Context, id uint) *Role {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RoleClient) Hooks() []Hook {
	return c.hooks.Role
}

// Interceptors returns the client interceptors.
func (c *RoleClient) Interceptors() []Interceptor {
	return c.inters.Role
}

func (c *RoleClient) mutate(ctx context.Context, m *RoleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RoleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RoleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RoleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Role mutation op: %q", m.Op())
	}
}

// RoleHasPermissionClient is a client for the RoleHasPermission schema.
type RoleHasPermissionClient struct {
	config
}

// NewRoleHasPermissionClient returns a client for the RoleHasPermission from the given config.
func NewRoleHasPermissionClient(c config) *RoleHasPermissionClient {
	return &RoleHasPermissionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `rolehaspermission.Hooks(f(g(h())))`.
func (c *RoleHasPermissionClient) Use(hooks ...Hook) {
	c.hooks.RoleHasPermission = append(c.hooks.RoleHasPermission, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `rolehaspermission.Intercept(f(g(h())))`.
func (c *RoleHasPermissionClient) Intercept(interceptors ...Interceptor) {
	c.inters.RoleHasPermission = append(c.inters.RoleHasPermission, interceptors...)
}

// Create returns a builder for creating a RoleHasPermission entity.
func (c *RoleHasPermissionClient) Create() *RoleHasPermissionCreate {
	mutation := newRoleHasPermissionMutation(c.config, OpCreate)
	return &RoleHasPermissionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RoleHasPermission entities.
func (c *RoleHasPermissionClient) CreateBulk(builders ...*RoleHasPermissionCreate) *RoleHasPermissionCreateBulk {
	return &RoleHasPermissionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RoleHasPermissionClient) MapCreateBulk(slice any, setFunc func(*RoleHasPermissionCreate, int)) *RoleHasPermissionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RoleHasPermissionCreateBulk{err: fmt.Errorf("calling to RoleHasPermissionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RoleHasPermissionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RoleHasPermissionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RoleHasPermission.
func (c *RoleHasPermissionClient) Update() *RoleHasPermissionUpdate {
	mutation := newRoleHasPermissionMutation(c.config, OpUpdate)
	return &RoleHasPermissionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RoleHasPermissionClient) UpdateOne(_m *RoleHasPermission) *RoleHasPermissionUpdateOne {
	mutation := newRoleHasPermissionMutation(c.config, OpUpdateOne, withRoleHasPermission(_m))
	return &RoleHasPermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RoleHasPermissionClient) UpdateOneID(id uint) *RoleHasPermissionUpdateOne {
	mutation := newRoleHasPermissionMutation(c.config, OpUpdateOne, withRoleHasPermissionID(id))
	return &RoleHasPermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RoleHasPermission.
func (c *RoleHasPermissionClient) Delete() *RoleHasPermissionDelete {
	mutation := newRoleHasPermissionMutation(c.config, OpDelete)
	return &RoleHasPermissionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RoleHasPermissionClient) DeleteOne(_m *RoleHasPermission) *RoleHasPermissionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RoleHasPermissionClient) DeleteOneID(id uint) *RoleHasPermissionDeleteOne {
	builder := c.Delete().Where(rolehaspermission.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RoleHasPermissionDeleteOne{builder}
}

// Query returns a query builder for RoleHasPermission.
func (c *RoleHasPermissionClient) Query() *RoleHasPermissionQuery {
	return &RoleHasPermissionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRoleHasPermission},
		inters: c.Interceptors(),
	}
}

// Get returns a RoleHasPermission entity by its id.
func (c *RoleHasPermissionClient) Get(ctx context.Context, id uint) (*RoleHasPermission, error) {
	return c.Query().Where(rolehaspermission.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RoleHasPermissionClient) GetX(ctx context.Context, id uint) *RoleHasPermission {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RoleHasPermissionClient) Hooks() []Hook {
	return c.hooks.RoleHasPermission
}

// Interceptors returns the client interceptors.
func (c *RoleHasPermissionClient) Interceptors() []Interceptor {
	return c.inters.RoleHasPermission
}

func (c *RoleHasPermissionClient) mutate(ctx context.Context, m *RoleHasPermissionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RoleHasPermissionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RoleHasPermissionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RoleHasPermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RoleHasPermissionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RoleHasPermission mutation op: %q", m.Op())
	}
}

// TenantClient is a client for the Tenant schema.
type TenantClient struct {
	config
}

// NewTenantClient returns a client for the Tenant from the given config.
func NewTenantClient(c config) *TenantClient {
	return &TenantClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tenant.Hooks(f(g(h())))`.
func (c *TenantClient) Use(hooks ...Hook) {
	c.hooks.Tenant = append(c.hooks.Tenant, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tenant.Intercept(f(g(h())))`.
func (c *TenantClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tenant = append(c.inters.Tenant, interceptors...)
}

// Create returns a builder for creating a Tenant entity.
func (c *TenantClient) Create() *TenantCreate {
	mutation := newTenantMutation(c.config, OpCreate)
	return &TenantCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tenant entities.
func (c *TenantClient) CreateBulk(builders ...*TenantCreate) *TenantCreateBulk {
	return &TenantCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TenantClient) MapCreateBulk(slice any, setFunc func(*TenantCreate, int)) *TenantCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TenantCreateBulk{err: fmt.Errorf("calling to TenantClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TenantCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TenantCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tenant.
func (c *TenantClient) Update() *TenantUpdate {
	mutation := newTenantMutation(c.config, OpUpdate)
	return &TenantUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TenantClient) UpdateOne(_m *Tenant) *TenantUpdateOne {
	mutation := newTenantMutation(c.config, OpUpdateOne, withTenant(_m))
	return &TenantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TenantClient) UpdateOneID(id string) *TenantUpdateOne {
	mutation := newTenantMutation(c.config, OpUpdateOne, withTenantID(id))
	return &TenantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tenant.
func (c *TenantClient) Delete() *TenantDelete {
	mutation := newTenantMutation(c.config, OpDelete)
	return &TenantDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TenantClient) DeleteOne(_m *Tenant) *TenantDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TenantClient) DeleteOneID(id string) *TenantDeleteOne {
	builder := c.Delete().Where(tenant.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TenantDeleteOne{builder}
}

// Query returns a query builder for Tenant.
func (c *TenantClient) Query() *TenantQuery {
	return &TenantQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTenant},
		inters: c.Interceptors(),
	}
}

// Get returns a Tenant entity by its id.
func (c *TenantClient) Get(ctx context.Context, id string) (*Tenant, error) {
	return c.Query().Where(tenant.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TenantClient) GetX(ctx context.Context, id string) *Tenant {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TenantClient) Hooks() []Hook {
	return c.hooks.Tenant
}

// Interceptors returns the client interceptors.
func (c *TenantClient) Interceptors() []Interceptor {
	return c.inters.Tenant
}

func (c *TenantClient) mutate(ctx context.Context, m *TenantMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TenantCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TenantUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TenantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TenantDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tenant mutation op: %q", m.Op())
	}
}

// TenantUserClient is a client for the TenantUser schema.
type TenantUserClient struct {
	config
}

// NewTenantUserClient returns a client for the TenantUser from the given config.
func NewTenantUserClient(c config) *TenantUserClient {
	return &TenantUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tenantuser.Hooks(f(g(h())))`.
func (c *TenantUserClient) Use(hooks ...Hook) {
	c.hooks.TenantUser = append(c.hooks.TenantUser, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tenantuser.Intercept(f(g(h())))`.
func (c *TenantUserClient) Intercept(interceptors ...Interceptor) {
	c.inters.TenantUser = append(c.inters.TenantUser, interceptors...)
}

// Create returns a builder for creating a TenantUser entity.
func (c *TenantUserClient) Create() *TenantUserCreate {
	mutation := newTenantUserMutation(c.config, OpCreate)
	return &TenantUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TenantUser entities.
func (c *TenantUserClient) CreateBulk(builders ...*TenantUserCreate) *TenantUserCreateBulk {
	return &TenantUserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TenantUserClient) MapCreateBulk(slice any, setFunc func(*TenantUserCreate, int)) *TenantUserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TenantUserCreateBulk{err: fmt.Errorf("calling to TenantUserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TenantUserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TenantUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TenantUser.
func (c *TenantUserClient) Update() *TenantUserUpdate {
	mutation := newTenantUserMutation(c.config, OpUpdate)
	return &TenantUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TenantUserClient) UpdateOne(_m *TenantUser) *TenantUserUpdateOne {
	mutation := newTenantUserMutation(c.config, OpUpdateOne, withTenantUser(_m))
	return &TenantUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TenantUserClient) UpdateOneID(id uint) *TenantUserUpdateOne {
	mutation := newTenantUserMutation(c.config, OpUpdateOne, withTenantUserID(id))
	return &TenantUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TenantUser.
func (c *TenantUserClient) Delete() *TenantUserDelete {
	mutation := newTenantUserMutation(c.config, OpDelete)
	return &TenantUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TenantUserClient) DeleteOne(_m *TenantUser) *TenantUserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TenantUserClient) DeleteOneID(id uint) *TenantUserDeleteOne {
	builder := c.Delete().Where(tenantuser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TenantUserDeleteOne{builder}
}

// Query returns a query builder for TenantUser.
func (c *TenantUserClient) Query() *TenantUserQuery {
	return &TenantUserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTenantUser},
		inters: c.Interceptors(),
	}
}

// Get returns a TenantUser entity by its id.
func (c *TenantUserClient) Get(ctx context.Context, id uint) (*TenantUser, error) {
	return c.Query().Where(tenantuser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TenantUserClient) GetX(ctx context.Context, id uint) *TenantUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TenantUserClient) Hooks() []Hook {
	return c.hooks.TenantUser
}

// Interceptors returns the client interceptors.
func (c *TenantUserClient) Interceptors() []Interceptor {
	return c.inters.TenantUser
}

func (c *TenantUserClient) mutate(ctx context.Context, m *TenantUserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TenantUserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TenantUserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TenantUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TenantUserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TenantUser mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ModelHasPermission, ModelHasRole, Permission, Role, RoleHasPermission, Tenant,
		TenantUser []ent.Hook
	}
	inters struct {
		ModelHasPermission, ModelHasRole, Permission, Role, RoleHasPermission, Tenant,
		TenantUser []ent.Interceptor
	}
)
