// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/permission/storage/entstore/ent/modelhaspermission"
	"github.com/mwangaben/permission/storage/entstore/ent/predicate"
)

// ModelHasPermissionUpdate is the builder for updating ModelHasPermission entities.
type ModelHasPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *ModelHasPermissionMutation
}

// Where appends a list predicates to the ModelHasPermissionUpdate builder.
func (_u *ModelHasPermissionUpdate) Where(ps ...predicate.ModelHasPermission) *ModelHasPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *ModelHasPermissionUpdate) SetPermissionID(v uint) *ModelHasPermissionUpdate {
	_u.mutation.ResetPermissionID()
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *ModelHasPermissionUpdate) SetNillablePermissionID(v *uint) *ModelHasPermissionUpdate {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// AddPermissionID adds value to the "permission_id" field.
func (_u *ModelHasPermissionUpdate) AddPermissionID(v int) *ModelHasPermissionUpdate {
	_u.mutation.AddPermissionID(v)
	return _u
}

// SetModelType sets the "model_type" field.
func (_u *ModelHasPermissionUpdate) SetModelType(v string) *ModelHasPermissionUpdate {
	_u.mutation.SetModelType(v)
	return _u
}

// SetNillableModelType sets the "model_type" field if the given value is not nil.
func (_u *ModelHasPermissionUpdate) SetNillableModelType(v *string) *ModelHasPermissionUpdate {
	if v != nil {
		_u.SetModelType(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelHasPermissionUpdate) SetModelID(v uint) *ModelHasPermissionUpdate {
	_u.mutation.ResetModelID()
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelHasPermissionUpdate) SetNillableModelID(v *uint) *ModelHasPermissionUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// AddModelID adds value to the "model_id" field.
func (_u *ModelHasPermissionUpdate) AddModelID(v int) *ModelHasPermissionUpdate {
	_u.mutation.AddModelID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ModelHasPermissionUpdate) SetTenantID(v string) *ModelHasPermissionUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ModelHasPermissionUpdate) SetNillableTenantID(v *string) *ModelHasPermissionUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *ModelHasPermissionUpdate) ClearTenantID() *ModelHasPermissionUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// Mutation returns the ModelHasPermissionMutation object of the builder.
func (_u *ModelHasPermissionUpdate) Mutation() *ModelHasPermissionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelHasPermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelHasPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelHasPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelHasPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelHasPermissionUpdate) check() error {
	if v, ok := _u.mutation.ModelType(); ok {
		if err := modelhaspermission.ModelTypeValidator(v); err != nil {
			return &ValidationError{Name: "model_type", err: fmt.Errorf(`ent: validator failed for field "ModelHasPermission.model_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := modelhaspermission.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ModelHasPermission.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelHasPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelhaspermission.Table, modelhaspermission.Columns, sqlgraph.NewFieldSpec(modelhaspermission.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PermissionID(); ok {
		_spec.SetField(modelhaspermission.FieldPermissionID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedPermissionID(); ok {
		_spec.AddField(modelhaspermission.FieldPermissionID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.ModelType(); ok {
		_spec.SetField(modelhaspermission.FieldModelType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelhaspermission.FieldModelID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedModelID(); ok {
		_spec.AddField(modelhaspermission.FieldModelID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(modelhaspermission.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(modelhaspermission.FieldTenantID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelhaspermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelHasPermissionUpdateOne is the builder for updating a single ModelHasPermission entity.
type ModelHasPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelHasPermissionMutation
}

// SetPermissionID sets the "permission_id" field.
func (_u *ModelHasPermissionUpdateOne) SetPermissionID(v uint) *ModelHasPermissionUpdateOne {
	_u.mutation.ResetPermissionID()
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *ModelHasPermissionUpdateOne) SetNillablePermissionID(v *uint) *ModelHasPermissionUpdateOne {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// AddPermissionID adds value to the "permission_id" field.
func (_u *ModelHasPermissionUpdateOne) AddPermissionID(v int) *ModelHasPermissionUpdateOne {
	_u.mutation.AddPermissionID(v)
	return _u
}

// SetModelType sets the "model_type" field.
func (_u *ModelHasPermissionUpdateOne) SetModelType(v string) *ModelHasPermissionUpdateOne {
	_u.mutation.SetModelType(v)
	return _u
}

// SetNillableModelType sets the "model_type" field if the given value is not nil.
func (_u *ModelHasPermissionUpdateOne) SetNillableModelType(v *string) *ModelHasPermissionUpdateOne {
	if v != nil {
		_u.SetModelType(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelHasPermissionUpdateOne) SetModelID(v uint) *ModelHasPermissionUpdateOne {
	_u.mutation.ResetModelID()
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelHasPermissionUpdateOne) SetNillableModelID(v *uint) *ModelHasPermissionUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// AddModelID adds value to the "model_id" field.
func (_u *ModelHasPermissionUpdateOne) AddModelID(v int) *ModelHasPermissionUpdateOne {
	_u.mutation.AddModelID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ModelHasPermissionUpdateOne) SetTenantID(v string) *ModelHasPermissionUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ModelHasPermissionUpdateOne) SetNillableTenantID(v *string) *ModelHasPermissionUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *ModelHasPermissionUpdateOne) ClearTenantID() *ModelHasPermissionUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// Mutation returns the ModelHasPermissionMutation object of the builder.
func (_u *ModelHasPermissionUpdateOne) Mutation() *ModelHasPermissionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelHasPermissionUpdate builder.
func (_u *ModelHasPermissionUpdateOne) Where(ps ...predicate.ModelHasPermission) *ModelHasPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelHasPermissionUpdateOne) Select(field string, fields ...string) *ModelHasPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelHasPermission entity.
func (_u *ModelHasPermissionUpdateOne) Save(ctx context.Context) (*ModelHasPermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelHasPermissionUpdateOne) SaveX(ctx context.Context) *ModelHasPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelHasPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelHasPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelHasPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.ModelType(); ok {
		if err := modelhaspermission.ModelTypeValidator(v); err != nil {
			return &ValidationError{Name: "model_type", err: fmt.Errorf(`ent: validator failed for field "ModelHasPermission.model_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := modelhaspermission.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ModelHasPermission.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelHasPermissionUpdateOne) sqlSave(ctx context.Context) (_node *ModelHasPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelhaspermission.Table, modelhaspermission.Columns, sqlgraph.NewFieldSpec(modelhaspermission.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelHasPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelhaspermission.FieldID)
		for _, f := range fields {
			if !modelhaspermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelhaspermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PermissionID(); ok {
		_spec.SetField(modelhaspermission.FieldPermissionID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedPermissionID(); ok {
		_spec.AddField(modelhaspermission.FieldPermissionID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.ModelType(); ok {
		_spec.SetField(modelhaspermission.FieldModelType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelhaspermission.FieldModelID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedModelID(); ok {
		_spec.AddField(modelhaspermission.FieldModelID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(modelhaspermission.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(modelhaspermission.FieldTenantID, field.TypeString)
	}
	_node = &ModelHasPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelhaspermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
