// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/permission/storage/entstore/ent/modelhaspermission"
	"github.com/mwangaben/permission/storage/entstore/ent/predicate"
)

// ModelHasPermissionDelete is the builder for deleting a ModelHasPermission entity.
type ModelHasPermissionDelete struct {
	config
	hooks    []Hook
	mutation *ModelHasPermissionMutation
}

// Where appends a list predicates to the ModelHasPermissionDelete builder.
func (_d *ModelHasPermissionDelete) Where(ps ...predicate.ModelHasPermission) *ModelHasPermissionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelHasPermissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelHasPermissionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelHasPermissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelhaspermission.Table, sqlgraph.NewFieldSpec(modelhaspermission.FieldID, field.TypeUint))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelHasPermissionDeleteOne is the builder for deleting a single ModelHasPermission entity.
type ModelHasPermissionDeleteOne struct {
	_d *ModelHasPermissionDelete
}

// Where appends a list predicates to the ModelHasPermissionDelete builder.
func (_d *ModelHasPermissionDeleteOne) Where(ps ...predicate.ModelHasPermission) *ModelHasPermissionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelHasPermissionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelhaspermission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelHasPermissionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
