// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/permission/storage/entstore/ent/modelhasrole"
	"github.com/mwangaben/permission/storage/entstore/ent/predicate"
)

// ModelHasRoleUpdate is the builder for updating ModelHasRole entities.
type ModelHasRoleUpdate struct {
	config
	hooks    []Hook
	mutation *ModelHasRoleMutation
}

// Where appends a list predicates to the ModelHasRoleUpdate builder.
func (_u *ModelHasRoleUpdate) Where(ps ...predicate.ModelHasRole) *ModelHasRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *ModelHasRoleUpdate) SetRoleID(v uint) *ModelHasRoleUpdate {
	_u.mutation.ResetRoleID()
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *ModelHasRoleUpdate) SetNillableRoleID(v *uint) *ModelHasRoleUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// AddRoleID adds value to the "role_id" field.
func (_u *ModelHasRoleUpdate) AddRoleID(v int) *ModelHasRoleUpdate {
	_u.mutation.AddRoleID(v)
	return _u
}

// SetModelType sets the "model_type" field.
func (_u *ModelHasRoleUpdate) SetModelType(v string) *ModelHasRoleUpdate {
	_u.mutation.SetModelType(v)
	return _u
}

// SetNillableModelType sets the "model_type" field if the given value is not nil.
func (_u *ModelHasRoleUpdate) SetNillableModelType(v *string) *ModelHasRoleUpdate {
	if v != nil {
		_u.SetModelType(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelHasRoleUpdate) SetModelID(v uint) *ModelHasRoleUpdate {
	_u.mutation.ResetModelID()
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelHasRoleUpdate) SetNillableModelID(v *uint) *ModelHasRoleUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// AddModelID adds value to the "model_id" field.
func (_u *ModelHasRoleUpdate) AddModelID(v int) *ModelHasRoleUpdate {
	_u.mutation.AddModelID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ModelHasRoleUpdate) SetTenantID(v string) *ModelHasRoleUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ModelHasRoleUpdate) SetNillableTenantID(v *string) *ModelHasRoleUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *ModelHasRoleUpdate) ClearTenantID() *ModelHasRoleUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// Mutation returns the ModelHasRoleMutation object of the builder.
func (_u *ModelHasRoleUpdate) Mutation() *ModelHasRoleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelHasRoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelHasRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelHasRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelHasRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelHasRoleUpdate) check() error {
	if v, ok := _u.mutation.ModelType(); ok {
		if err := modelhasrole.ModelTypeValidator(v); err != nil {
			return &ValidationError{Name: "model_type", err: fmt.Errorf(`ent: validator failed for field "ModelHasRole.model_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := modelhasrole.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ModelHasRole.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelHasRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelhasrole.Table, modelhasrole.Columns, sqlgraph.NewFieldSpec(modelhasrole.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(modelhasrole.FieldRoleID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedRoleID(); ok {
		_spec.AddField(modelhasrole.FieldRoleID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.ModelType(); ok {
		_spec.SetField(modelhasrole.FieldModelType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelhasrole.FieldModelID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedModelID(); ok {
		_spec.AddField(modelhasrole.FieldModelID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(modelhasrole.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(modelhasrole.FieldTenantID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelhasrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelHasRoleUpdateOne is the builder for updating a single ModelHasRole entity.
type ModelHasRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelHasRoleMutation
}

// SetRoleID sets the "role_id" field.
func (_u *ModelHasRoleUpdateOne) SetRoleID(v uint) *ModelHasRoleUpdateOne {
	_u.mutation.ResetRoleID()
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *ModelHasRoleUpdateOne) SetNillableRoleID(v *uint) *ModelHasRoleUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// AddRoleID adds value to the "role_id" field.
func (_u *ModelHasRoleUpdateOne) AddRoleID(v int) *ModelHasRoleUpdateOne {
	_u.mutation.AddRoleID(v)
	return _u
}

// SetModelType sets the "model_type" field.
func (_u *ModelHasRoleUpdateOne) SetModelType(v string) *ModelHasRoleUpdateOne {
	_u.mutation.SetModelType(v)
	return _u
}

// SetNillableModelType sets the "model_type" field if the given value is not nil.
func (_u *ModelHasRoleUpdateOne) SetNillableModelType(v *string) *ModelHasRoleUpdateOne {
	if v != nil {
		_u.SetModelType(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelHasRoleUpdateOne) SetModelID(v uint) *ModelHasRoleUpdateOne {
	_u.mutation.ResetModelID()
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelHasRoleUpdateOne) SetNillableModelID(v *uint) *ModelHasRoleUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// AddModelID adds value to the "model_id" field.
func (_u *ModelHasRoleUpdateOne) AddModelID(v int) *ModelHasRoleUpdateOne {
	_u.mutation.AddModelID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ModelHasRoleUpdateOne) SetTenantID(v string) *ModelHasRoleUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ModelHasRoleUpdateOne) SetNillableTenantID(v *string) *ModelHasRoleUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *ModelHasRoleUpdateOne) ClearTenantID() *ModelHasRoleUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// Mutation returns the ModelHasRoleMutation object of the builder.
func (_u *ModelHasRoleUpdateOne) Mutation() *ModelHasRoleMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelHasRoleUpdate builder.
func (_u *ModelHasRoleUpdateOne) Where(ps ...predicate.ModelHasRole) *ModelHasRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelHasRoleUpdateOne) Select(field string, fields ...string) *ModelHasRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelHasRole entity.
func (_u *ModelHasRoleUpdateOne) Save(ctx context.Context) (*ModelHasRole, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelHasRoleUpdateOne) SaveX(ctx context.Context) *ModelHasRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelHasRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelHasRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelHasRoleUpdateOne) check() error {
	if v, ok := _u.mutation.ModelType(); ok {
		if err := modelhasrole.ModelTypeValidator(v); err != nil {
			return &ValidationError{Name: "model_type", err: fmt.Errorf(`ent: validator failed for field "ModelHasRole.model_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := modelhasrole.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ModelHasRole.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelHasRoleUpdateOne) sqlSave(ctx context.Context) (_node *ModelHasRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelhasrole.Table, modelhasrole.Columns, sqlgraph.NewFieldSpec(modelhasrole.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelHasRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelhasrole.FieldID)
		for _, f := range fields {
			if !modelhasrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelhasrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(modelhasrole.FieldRoleID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedRoleID(); ok {
		_spec.AddField(modelhasrole.FieldRoleID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.ModelType(); ok {
		_spec.SetField(modelhasrole.FieldModelType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelhasrole.FieldModelID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedModelID(); ok {
		_spec.AddField(modelhasrole.FieldModelID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(modelhasrole.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(modelhasrole.FieldTenantID, field.TypeString)
	}
	_node = &ModelHasRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelhasrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
