// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/permission/storage/entstore/ent/modelhasrole"
	"github.com/mwangaben/permission/storage/entstore/ent/predicate"
)

// ModelHasRoleDelete is the builder for deleting a ModelHasRole entity.
type ModelHasRoleDelete struct {
	config
	hooks    []Hook
	mutation *ModelHasRoleMutation
}

// Where appends a list predicates to the ModelHasRoleDelete builder.
func (_d *ModelHasRoleDelete) Where(ps ...predicate.ModelHasRole) *ModelHasRoleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelHasRoleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelHasRoleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelHasRoleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelhasrole.Table, sqlgraph.NewFieldSpec(modelhasrole.FieldID, field.TypeUint))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelHasRoleDeleteOne is the builder for deleting a single ModelHasRole entity.
type ModelHasRoleDeleteOne struct {
	_d *ModelHasRoleDelete
}

// Where appends a list predicates to the ModelHasRoleDelete builder.
func (_d *ModelHasRoleDeleteOne) Where(ps ...predicate.ModelHasRole) *ModelHasRoleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelHasRoleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelhasrole.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelHasRoleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
