// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mwangaben/permission/storage/entstore/ent/modelhaspermission"
)

// ModelHasPermission is the model entity for the ModelHasPermission schema.
type ModelHasPermission struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// PermissionID holds the value of the "permission_id" field.
	PermissionID uint `json:"permission_id,omitempty"`
	// ModelType holds the value of the "model_type" field.
	ModelType string `json:"model_type,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID uint `json:"model_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID     *string `json:"tenant_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelHasPermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelhaspermission.FieldID, modelhaspermission.FieldPermissionID, modelhaspermission.FieldModelID:
			values[i] = new(sql.NullInt64)
		case modelhaspermission.FieldModelType, modelhaspermission.FieldTenantID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelHasPermission fields.
func (_m *ModelHasPermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelhaspermission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case modelhaspermission.FieldPermissionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value.Valid {
				_m.PermissionID = uint(value.Int64)
			}
		case modelhaspermission.FieldModelType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_type", values[i])
			} else if value.Valid {
				_m.ModelType = value.String
			}
		case modelhaspermission.FieldModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = uint(value.Int64)
			}
		case modelhaspermission.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(string)
				*_m.TenantID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelHasPermission.
// This includes values selected through modifiers, order, etc.
func (_m *ModelHasPermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelHasPermission.
// Note that you need to call ModelHasPermission.Unwrap() before calling this method if this ModelHasPermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelHasPermission) Update() *ModelHasPermissionUpdateOne {
	return NewModelHasPermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelHasPermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelHasPermission) Unwrap() *ModelHasPermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelHasPermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelHasPermission) String() string {
	var builder strings.Builder
	builder.WriteString("ModelHasPermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("permission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionID))
	builder.WriteString(", ")
	builder.WriteString("model_type=")
	builder.WriteString(_m.ModelType)
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelID))
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModelHasPermissions is a parsable slice of ModelHasPermission.
type ModelHasPermissions []*ModelHasPermission
