// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/permission/storage/entstore/ent/predicate"
	"github.com/mwangaben/permission/storage/entstore/ent/rolehaspermission"
)

// RoleHasPermissionUpdate is the builder for updating RoleHasPermission entities.
type RoleHasPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *RoleHasPermissionMutation
}

// Where appends a list predicates to the RoleHasPermissionUpdate builder.
func (_u *RoleHasPermissionUpdate) Where(ps ...predicate.RoleHasPermission) *RoleHasPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPermissionID sets the "permission_id" field.
func (_u *RoleHasPermissionUpdate) SetPermissionID(v uint) *RoleHasPermissionUpdate {
	_u.mutation.ResetPermissionID()
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *RoleHasPermissionUpdate) SetNillablePermissionID(v *uint) *RoleHasPermissionUpdate {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// AddPermissionID adds value to the "permission_id" field.
func (_u *RoleHasPermissionUpdate) AddPermissionID(v int) *RoleHasPermissionUpdate {
	_u.mutation.AddPermissionID(v)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *RoleHasPermissionUpdate) SetRoleID(v uint) *RoleHasPermissionUpdate {
	_u.mutation.ResetRoleID()
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *RoleHasPermissionUpdate) SetNillableRoleID(v *uint) *RoleHasPermissionUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// AddRoleID adds value to the "role_id" field.
func (_u *RoleHasPermissionUpdate) AddRoleID(v int) *RoleHasPermissionUpdate {
	_u.mutation.AddRoleID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *RoleHasPermissionUpdate) SetTenantID(v string) *RoleHasPermissionUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *RoleHasPermissionUpdate) SetNillableTenantID(v *string) *RoleHasPermissionUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *RoleHasPermissionUpdate) ClearTenantID() *RoleHasPermissionUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// Mutation returns the RoleHasPermissionMutation object of the builder.
func (_u *RoleHasPermissionUpdate) Mutation() *RoleHasPermissionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoleHasPermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoleHasPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoleHasPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoleHasPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoleHasPermissionUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := rolehaspermission.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "RoleHasPermission.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (_u *RoleHasPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolehaspermission.Table, rolehaspermission.Columns, sqlgraph.NewFieldSpec(rolehaspermission.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PermissionID(); ok {
		_spec.SetField(rolehaspermission.FieldPermissionID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedPermissionID(); ok {
		_spec.AddField(rolehaspermission.FieldPermissionID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(rolehaspermission.FieldRoleID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedRoleID(); ok {
		_spec.AddField(rolehaspermission.FieldRoleID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(rolehaspermission.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(rolehaspermission.FieldTenantID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolehaspermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoleHasPermissionUpdateOne is the builder for updating a single RoleHasPermission entity.
type RoleHasPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoleHasPermissionMutation
}

// SetPermissionID sets the "permission_id" field.
func (_u *RoleHasPermissionUpdateOne) SetPermissionID(v uint) *RoleHasPermissionUpdateOne {
	_u.mutation.ResetPermissionID()
	_u.mutation.SetPermissionID(v)
	return _u
}

// SetNillablePermissionID sets the "permission_id" field if the given value is not nil.
func (_u *RoleHasPermissionUpdateOne) SetNillablePermissionID(v *uint) *RoleHasPermissionUpdateOne {
	if v != nil {
		_u.SetPermissionID(*v)
	}
	return _u
}

// AddPermissionID adds value to the "permission_id" field.
func (_u *RoleHasPermissionUpdateOne) AddPermissionID(v int) *RoleHasPermissionUpdateOne {
	_u.mutation.AddPermissionID(v)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *RoleHasPermissionUpdateOne) SetRoleID(v uint) *RoleHasPermissionUpdateOne {
	_u.mutation.ResetRoleID()
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *RoleHasPermissionUpdateOne) SetNillableRoleID(v *uint) *RoleHasPermissionUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// AddRoleID adds value to the "role_id" field.
func (_u *RoleHasPermissionUpdateOne) AddRoleID(v int) *RoleHasPermissionUpdateOne {
	_u.mutation.AddRoleID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *RoleHasPermissionUpdateOne) SetTenantID(v string) *RoleHasPermissionUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *RoleHasPermissionUpdateOne) SetNillableTenantID(v *string) *RoleHasPermissionUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *RoleHasPermissionUpdateOne) ClearTenantID() *RoleHasPermissionUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// Mutation returns the RoleHasPermissionMutation object of the builder.
func (_u *RoleHasPermissionUpdateOne) Mutation() *RoleHasPermissionMutation {
	return _u.mutation
}

// Where appends a list predicates to the RoleHasPermissionUpdate builder.
func (_u *RoleHasPermissionUpdateOne) Where(ps ...predicate.RoleHasPermission) *RoleHasPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoleHasPermissionUpdateOne) Select(field string, fields ...string) *RoleHasPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RoleHasPermission entity.
func (_u *RoleHasPermissionUpdateOne) Save(ctx context.Context) (*RoleHasPermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoleHasPermissionUpdateOne) SaveX(ctx context.Context) *RoleHasPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoleHasPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoleHasPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoleHasPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := rolehaspermission.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "RoleHasPermission.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (_u *RoleHasPermissionUpdateOne) sqlSave(ctx context.Context) (_node *RoleHasPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolehaspermission.Table, rolehaspermission.Columns, sqlgraph.NewFieldSpec(rolehaspermission.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoleHasPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rolehaspermission.FieldID)
		for _, f := range fields {
			if !rolehaspermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rolehaspermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PermissionID(); ok {
		_spec.SetField(rolehaspermission.FieldPermissionID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedPermissionID(); ok {
		_spec.AddField(rolehaspermission.FieldPermissionID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(rolehaspermission.FieldRoleID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedRoleID(); ok {
		_spec.AddField(rolehaspermission.FieldRoleID, field.TypeUint, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(rolehaspermission.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(rolehaspermission.FieldTenantID, field.TypeString)
	}
	_node = &RoleHasPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolehaspermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
