// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mwangaben/permission/storage/entstore/ent/rolehaspermission"
)

// RoleHasPermission is the model entity for the RoleHasPermission schema.
type RoleHasPermission struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// PermissionID holds the value of the "permission_id" field.
	PermissionID uint `json:"permission_id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID uint `json:"role_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID     *string `json:"tenant_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RoleHasPermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rolehaspermission.FieldID, rolehaspermission.FieldPermissionID, rolehaspermission.FieldRoleID:
			values[i] = new(sql.NullInt64)
		case rolehaspermission.FieldTenantID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RoleHasPermission fields.
func (_m *RoleHasPermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rolehaspermission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint(value.Int64)
		case rolehaspermission.FieldPermissionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value.Valid {
				_m.PermissionID = uint(value.Int64)
			}
		case rolehaspermission.FieldRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = uint(value.Int64)
			}
		case rolehaspermission.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(string)
				*_m.TenantID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RoleHasPermission.
// This includes values selected through modifiers, order, etc.
func (_m *RoleHasPermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RoleHasPermission.
// Note that you need to call RoleHasPermission.Unwrap() before calling this method if this RoleHasPermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RoleHasPermission) Update() *RoleHasPermissionUpdateOne {
	return NewRoleHasPermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RoleHasPermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RoleHasPermission) Unwrap() *RoleHasPermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RoleHasPermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RoleHasPermission) String() string {
	var builder strings.Builder
	builder.WriteString("RoleHasPermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("permission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// RoleHasPermissions is a parsable slice of RoleHasPermission.
type RoleHasPermissions []*RoleHasPermission
