// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mwangaben/permission/storage/entstore/ent/rolehaspermission"
)

// RoleHasPermissionCreate is the builder for creating a RoleHasPermission entity.
type RoleHasPermissionCreate struct {
	config
	mutation *RoleHasPermissionMutation
	hooks    []Hook
}

// SetPermissionID sets the "permission_id" field.
func (_c *RoleHasPermissionCreate) SetPermissionID(v uint) *RoleHasPermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *RoleHasPermissionCreate) SetRoleID(v uint) *RoleHasPermissionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *RoleHasPermissionCreate) SetTenantID(v string) *RoleHasPermissionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *RoleHasPermissionCreate) SetNillableTenantID(v *string) *RoleHasPermissionCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RoleHasPermissionCreate) SetID(v uint) *RoleHasPermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RoleHasPermissionMutation object of the builder.
func (_c *RoleHasPermissionCreate) Mutation() *RoleHasPermissionMutation {
	return _c.mutation
}

// Save creates the RoleHasPermission in the database.
func (_c *RoleHasPermissionCreate) Save(ctx context.Context) (*RoleHasPermission, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoleHasPermissionCreate) SaveX(ctx context.Context) *RoleHasPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoleHasPermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoleHasPermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoleHasPermissionCreate) check() error {
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "RoleHasPermission.permission_id"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "RoleHasPermission.role_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := rolehaspermission.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "RoleHasPermission.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (_c *RoleHasPermissionCreate) sqlSave(ctx context.Context) (*RoleHasPermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoleHasPermissionCreate) createSpec() (*RoleHasPermission, *sqlgraph.CreateSpec) {
	var (
		_node = &RoleHasPermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rolehaspermission.Table, sqlgraph.NewFieldSpec(rolehaspermission.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PermissionID(); ok {
		_spec.SetField(rolehaspermission.FieldPermissionID, field.TypeUint, value)
		_node.PermissionID = value
	}
	if value, ok := _c.mutation.RoleID(); ok {
		_spec.SetField(rolehaspermission.FieldRoleID, field.TypeUint, value)
		_node.RoleID = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(rolehaspermission.FieldTenantID, field.TypeString, value)
		_node.TenantID = &value
	}
	return _node, _spec
}

// RoleHasPermissionCreateBulk is the builder for creating many RoleHasPermission entities in bulk.
type RoleHasPermissionCreateBulk struct {
	config
	err      error
	builders []*RoleHasPermissionCreate
}

// Save creates the RoleHasPermission entities in the database.
func (_c *RoleHasPermissionCreateBulk) Save(ctx context.Context) ([]*RoleHasPermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoleHasPermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoleHasPermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoleHasPermissionCreateBulk) SaveX(ctx context.Context) []*RoleHasPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoleHasPermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoleHasPermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
