// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mwangaben/permission/storage/entstore/ent/modelhaspermission"
	"github.com/mwangaben/permission/storage/entstore/ent/modelhasrole"
	"github.com/mwangaben/permission/storage/entstore/ent/permission"
	"github.com/mwangaben/permission/storage/entstore/ent/role"
	"github.com/mwangaben/permission/storage/entstore/ent/rolehaspermission"
	"github.com/mwangaben/permission/storage/entstore/ent/tenant"
	"github.com/mwangaben/permission/storage/entstore/ent/tenantuser"
	"github.com/mwangaben/permission/storage/entstore/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	modelhaspermissionFields := schema.ModelHasPermission{}.Fields()
	_ = modelhaspermissionFields
	// modelhaspermissionDescModelType is the schema descriptor for model_type field.
	modelhaspermissionDescModelType := modelhaspermissionFields[2].Descriptor()
	// modelhaspermission.ModelTypeValidator is a validator for the "model_type" field. It is called by the builders before save.
	modelhaspermission.ModelTypeValidator = func() func(string) error {
		validators := modelhaspermissionDescModelType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model_type string) error {
			for _, fn := range fns {
				if err := fn(model_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// modelhaspermissionDescTenantID is the schema descriptor for tenant_id field.
	modelhaspermissionDescTenantID := modelhaspermissionFields[4].Descriptor()
	// modelhaspermission.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	modelhaspermission.TenantIDValidator = modelhaspermissionDescTenantID.Validators[0].(func(string) error)
	modelhasroleFields := schema.ModelHasRole{}.Fields()
	_ = modelhasroleFields
	// modelhasroleDescModelType is the schema descriptor for model_type field.
	modelhasroleDescModelType := modelhasroleFields[2].Descriptor()
	// modelhasrole.ModelTypeValidator is a validator for the "model_type" field. It is called by the builders before save.
	modelhasrole.ModelTypeValidator = func() func(string) error {
		validators := modelhasroleDescModelType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model_type string) error {
			for _, fn := range fns {
				if err := fn(model_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// modelhasroleDescTenantID is the schema descriptor for tenant_id field.
	modelhasroleDescTenantID := modelhasroleFields[4].Descriptor()
	// modelhasrole.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	modelhasrole.TenantIDValidator = modelhasroleDescTenantID.Validators[0].(func(string) error)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescName is the schema descriptor for name field.
	permissionDescName := permissionFields[1].Descriptor()
	// permission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	permission.NameValidator = func() func(string) error {
		validators := permissionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescGuardName is the schema descriptor for guard_name field.
	permissionDescGuardName := permissionFields[2].Descriptor()
	// permission.DefaultGuardName holds the default value on creation for the guard_name field.
	permission.DefaultGuardName = permissionDescGuardName.Default.(string)
	// permission.GuardNameValidator is a validator for the "guard_name" field. It is called by the builders before save.
	permission.GuardNameValidator = permissionDescGuardName.Validators[0].(func(string) error)
	// permissionDescTenantID is the schema descriptor for tenant_id field.
	permissionDescTenantID := permissionFields[3].Descriptor()
	// permission.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	permission.TenantIDValidator = permissionDescTenantID.Validators[0].(func(string) error)
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[4].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionFields[5].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[1].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = func() func(string) error {
		validators := roleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescGuardName is the schema descriptor for guard_name field.
	roleDescGuardName := roleFields[2].Descriptor()
	// role.DefaultGuardName holds the default value on creation for the guard_name field.
	role.DefaultGuardName = roleDescGuardName.Default.(string)
	// role.GuardNameValidator is a validator for the "guard_name" field. It is called by the builders before save.
	role.GuardNameValidator = roleDescGuardName.Validators[0].(func(string) error)
	// roleDescTenantID is the schema descriptor for tenant_id field.
	roleDescTenantID := roleFields[3].Descriptor()
	// role.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	role.TenantIDValidator = roleDescTenantID.Validators[0].(func(string) error)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[4].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[5].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	rolehaspermissionFields := schema.RoleHasPermission{}.Fields()
	_ = rolehaspermissionFields
	// rolehaspermissionDescTenantID is the schema descriptor for tenant_id field.
	rolehaspermissionDescTenantID := rolehaspermissionFields[3].Descriptor()
	// rolehaspermission.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	rolehaspermission.TenantIDValidator = rolehaspermissionDescTenantID.Validators[0].(func(string) error)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = func() func(string) error {
		validators := tenantDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[2].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = func() func(string) error {
		validators := tenantDescSlug.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(slug string) error {
			for _, fn := range fns {
				if err := fn(slug); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescDomain is the schema descriptor for domain field.
	tenantDescDomain := tenantFields[3].Descriptor()
	// tenant.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	tenant.DomainValidator = tenantDescDomain.Validators[0].(func(string) error)
	// tenantDescLogo is the schema descriptor for logo field.
	tenantDescLogo := tenantFields[4].Descriptor()
	// tenant.LogoValidator is a validator for the "logo" field. It is called by the builders before save.
	tenant.LogoValidator = tenantDescLogo.Validators[0].(func(string) error)
	// tenantDescActive is the schema descriptor for active field.
	tenantDescActive := tenantFields[5].Descriptor()
	// tenant.DefaultActive holds the default value on creation for the active field.
	tenant.DefaultActive = tenantDescActive.Default.(bool)
	// tenantDescOwnerID is the schema descriptor for owner_id field.
	tenantDescOwnerID := tenantFields[6].Descriptor()
	// tenant.OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	tenant.OwnerIDValidator = tenantDescOwnerID.Validators[0].(func(string) error)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[9].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[10].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.IDValidator is a validator for the "id" field. It is called by the builders before save.
	tenant.IDValidator = tenantDescID.Validators[0].(func(string) error)
	tenantuserFields := schema.TenantUser{}.Fields()
	_ = tenantuserFields
	// tenantuserDescUserID is the schema descriptor for user_id field.
	tenantuserDescUserID := tenantuserFields[1].Descriptor()
	// tenantuser.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	tenantuser.UserIDValidator = tenantuserDescUserID.Validators[0].(func(string) error)
	// tenantuserDescTenantID is the schema descriptor for tenant_id field.
	tenantuserDescTenantID := tenantuserFields[2].Descriptor()
	// tenantuser.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	tenantuser.TenantIDValidator = tenantuserDescTenantID.Validators[0].(func(string) error)
	// tenantuserDescCreatedAt is the schema descriptor for created_at field.
	tenantuserDescCreatedAt := tenantuserFields[3].Descriptor()
	// tenantuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantuser.DefaultCreatedAt = tenantuserDescCreatedAt.Default.(func() time.Time)
	// tenantuserDescUpdatedAt is the schema descriptor for updated_at field.
	tenantuserDescUpdatedAt := tenantuserFields[4].Descriptor()
	// tenantuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantuser.DefaultUpdatedAt = tenantuserDescUpdatedAt.Default.(func() time.Time)
	// tenantuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenantuser.UpdateDefaultUpdatedAt = tenantuserDescUpdatedAt.UpdateDefault.(func() time.Time)
}
